# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{policymap_wrap}
  s.version = "0.4.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Mauricio Gomes"]
  s.date = %q{2011-04-27}
  s.description = %q{Ruby wrapper around the PolicyMap API. Your API may vary.}
  s.email = %q{mauricio@geminisbs.com}
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc"
  ]
  s.files = [
    "LICENSE",
    "README.rdoc",
    "VERSION",
    "lib/policymap.rb",
    "lib/policymap_wrap.rb",
    "lib/policymap_wrap/client.rb",
    "lib/policymap_wrap/connection.rb",
    "lib/policymap_wrap/endpoint.rb",
    "lib/policymap_wrap/hash_utils.rb"
  ]
  s.homepage = %q{http://github.com/geminisbs/policymap_wrap}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.5.2}
  s.summary = %q{Ruby wrapper around the PolicyMap API}
  s.test_files = [
    "spec/policymap_wrap_spec.rb",
    "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<yajl-ruby>, [">= 0.7.7"])
      s.add_runtime_dependency(%q<curb>, [">= 0.7.7.1"])
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
    else
      s.add_dependency(%q<yajl-ruby>, [">= 0.7.7"])
      s.add_dependency(%q<curb>, [">= 0.7.7.1"])
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
    end
  else
    s.add_dependency(%q<yajl-ruby>, [">= 0.7.7"])
    s.add_dependency(%q<curb>, [">= 0.7.7.1"])
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
  end
end

